"""Showdown in the Badlands — Excavate treasure pool (non-collectible
WW_001t* cards generated by the Excavate keyword)."""

from ..utils import *


##
# Tier-1 treasures (1-Cost)


class WW_001t:
	"""Rock"""

	# Deal $3 damage.
	requirements = {PlayReq.REQ_TARGET_TO_PLAY: 0}
	play = Hit(TARGET, 3)


class WW_001t18:
	"""Pouch of Coins"""

	# Get two Coins. (The Coin is GAME_005.)
	play = Give(CONTROLLER, "GAME_005") * 2


class WW_001t2:
	"""Water Source"""

	# Restore #3 Health. Draw a card.
	requirements = {PlayReq.REQ_TARGET_TO_PLAY: 0}
	play = Heal(TARGET, 3), Draw(CONTROLLER)


# Discover a 2-Cost card. It costs (0).
_FoolsAzerite = lambda: Discover(CONTROLLER, RandomCard(cost=2)).then(
	Give(CONTROLLER, Discover.CARD),
	Buff(Give.CARD, "WW_001t3e"),
)


class WW_001t3:
	"""Fool's Azerite"""

	play = _FoolsAzerite()


@custom_card
class WW_001t3e:
	# "It costs (0)." — engine clamps negative cost to 0.
	tags = {
		GameTag.CARDNAME: "Fool's Azerite",
		GameTag.CARDTYPE: CardType.ENCHANTMENT,
		GameTag.COST: -100,
	}


class WW_001t4:
	"""Escaping Trogg"""

	# Rush (data-only keyword).


##
# Tier-2 treasures (2-Cost)


class WW_001t16:
	"""Living Stone"""

	# Taunt (data). Deathrattle: Summon a random 2-Cost minion.
	deathrattle = Summon(CONTROLLER, RandomMinion(cost=2))


class WW_001t5:
	"""Falling Stalactite"""

	# Deal $3 damage to a minion and the enemy hero.
	requirements = {
		PlayReq.REQ_TARGET_TO_PLAY: 0,
		PlayReq.REQ_MINION_TARGET: 0,
	}
	play = Hit(TARGET, 3), Hit(ENEMY_HERO, 3)


class WW_001t7:
	"""Canary"""

	# Battlecry: Return an enemy minion to its owner's hand.
	requirements = {
		PlayReq.REQ_TARGET_TO_PLAY: 0,
		PlayReq.REQ_MINION_TARGET: 0,
		PlayReq.REQ_ENEMY_TARGET: 0,
	}
	play = Bounce(TARGET)


class WW_001t8:
	"""Glowing Glyph"""

	# Give a minion and its neighbors +1/+2.
	requirements = {
		PlayReq.REQ_TARGET_TO_PLAY: 0,
		PlayReq.REQ_MINION_TARGET: 0,
	}
	play = Buff(TARGET, "WW_001t8e"), Buff(TARGET_ADJACENT, "WW_001t8e")


WW_001t8e = buff(atk=1, health=2)  # Glowing Glyph — +1/+2


# Discover a 3-Cost card. It costs (0).
_AzeriteChunk = lambda: Discover(CONTROLLER, RandomCard(cost=3)).then(
	Give(CONTROLLER, Discover.CARD),
	Buff(Give.CARD, "WW_001t9e"),
)


class WW_001t9:
	"""Azerite Chunk"""

	play = _AzeriteChunk()


@custom_card
class WW_001t9e:
	tags = {
		GameTag.CARDNAME: "Azerite Chunk",
		GameTag.CARDTYPE: CardType.ENCHANTMENT,
		GameTag.COST: -100,
	}


##
# Tier-3 treasures (3-Cost)


class WW_001t11:
	"""Ogrefist Boulder"""

	# Location. Activate: Set a minion's stats to 6/7.
	requirements = {
		PlayReq.REQ_TARGET_TO_PLAY: 0,
		PlayReq.REQ_MINION_TARGET: 0,
	}
	activate = Buff(TARGET, "WW_001t11e"), SetCurrentHealth(TARGET, 7)


class WW_001t11e:
	# Set stats to 6/7 (Good Stats — exists in data, supply the SET tags).
	atk = SET(6)
	max_health = SET(7)


class WW_001t12:
	"""Collapse!"""

	# Deal $3 damage to all enemies.
	play = Hit(ENEMY_CHARACTERS, 3)


class WW_001t13:
	"""Steelhide Mole"""

	# Taunt, Reborn, Can't be targeted by spells or Hero Powers (data-only).


# Discover a 5-Cost card. It costs (0).
_AzeriteGem = lambda: Discover(CONTROLLER, RandomCard(cost=5)).then(
	Give(CONTROLLER, Discover.CARD),
	Buff(Give.CARD, "WW_001t14e"),
)


class WW_001t14:
	"""Azerite Gem"""

	play = _AzeriteGem()


class WW_001t14e:
	# "It costs (0)." — exists in data; supply the cost clamp.
	tags = {GameTag.COST: -100}


class WW_001t17:
	"""Motherlode Drake"""

	# Rush, Divine Shield, Lifesteal (data-only keywords).


##
# Tier-4 treasures (4-Cost LEGENDARY — "The Azerite ..." class payoffs)


# Battlecry: Get 4 random spells. If you've Excavated 8 times, they
# cost (0). We resolve the picks ourselves so each gained spell can be
# reliably located in hand and (when zeroed) buffed.
class _AzeriteScorpionGet(TargetedAction):
	TARGET = ActionArg()

	def do(self, source, target):
		zero = target.excavates_this_game >= 8
		for _ in range(4):
			pick = RandomSpell().evaluate(source)
			cid = pick[0] if isinstance(pick, (list, tuple)) else pick
			if not cid:
				continue
			before = set(id(c) for c in target.hand)
			source.game.cheat_action(source, [Give(target, cid)])
			if not zero:
				continue
			for card in target.hand:
				if id(card) not in before:
					source.game.cheat_action(
						source, [Buff(card, "WW_001t23e")]
					)


class WW_001t23:
	"""The Azerite Scorpion"""

	play = _AzeriteScorpionGet(CONTROLLER)


@custom_card
class WW_001t23e:
	# Scorpion's Sting — "they cost (0)" (exists in data as an empty shell;
	# we re-register with the cost clamp so the effect actually applies).
	tags = {
		GameTag.CARDNAME: "Scorpion's Sting",
		GameTag.CARDTYPE: CardType.ENCHANTMENT,
		GameTag.COST: -100,
	}


# Battlecry: Get a random Titan. It costs (1). Titans carry the
# DONT_PICK_FROM_SUBSETS tag, so they only surface from the card pool when
# can_pick_from_subsets is passed. We resolve the pick, give the card, then
# buff the freshly-added hand card to cost (1).
class _AzeriteHawkGet(TargetedAction):
	TARGET = ActionArg()

	def do(self, source, target):
		picker = RandomMinion(
			can_pick_from_subsets=True,
			custom_filter=lambda c: bool(getattr(c, "titan", False)),
		)
		pick = picker.evaluate(source)
		cid = pick[0] if isinstance(pick, (list, tuple)) else pick
		if not cid:
			return
		before = set(id(c) for c in target.hand)
		source.game.cheat_action(source, [Give(target, cid)])
		for card in target.hand:
			if id(card) not in before:
				source.game.cheat_action(source, [Buff(card, "WW_001t24e")])


class WW_001t24:
	"""The Azerite Hawk"""

	play = _AzeriteHawkGet(CONTROLLER)


@custom_card
class WW_001t24e:
	# "It costs (1)." — SET the Titan's cost to exactly 1 (DMF_071e idiom;
	# SET() must be a class attr, never in the tags dict).
	tags = {
		GameTag.CARDNAME: "The Azerite Hawk",
		GameTag.CARDTYPE: CardType.ENCHANTMENT,
	}
	cost = SET(1)


class WW_001t25:
	"""The Azerite Snake"""

	# Battlecry: Your hero steals 10 Health from the enemy hero.
	play = Hit(ENEMY_HERO, 10), Heal(FRIENDLY_HERO, 10)


class WW_001t26:
	"""The Azerite Rat"""

	# Battlecry: Resurrect your highest Cost minion. Give it +2/+2,
	# Reborn, and Lifesteal.
	play = Summon(CONTROLLER, Copy(HIGHEST_COST(FRIENDLY + KILLED + MINION))).then(
		Buff(Summon.CARD, "WW_001t26e"),
		GiveReborn(Summon.CARD),
		GiveLifesteal(Summon.CARD),
	)


WW_001t26e = buff(atk=2, health=2)  # Azerite Soul — +2/+2


# Battlecry: Discover two 8-Cost minions. Summon them. Resolve the two
# discovers sequentially via a re-entrant action so the choices don't
# stomp on each other (flat Discover tuples all set player.choice at once
# and only the last survives — see CLAUDE.md).
class _AzeriteOxDiscover(TargetedAction):
	TARGET = ActionArg()

	def do(self, source, target):
		remaining = getattr(source, "_azerite_ox_left", None)
		if remaining is None:
			remaining = 2
		if remaining <= 0:
			source._azerite_ox_left = None
			return
		source._azerite_ox_left = remaining - 1
		source.game.cheat_action(
			source,
			[
				Discover(target, RandomMinion(cost=8)).then(
					Summon(target, Discover.CARD),
					_AzeriteOxDiscover(target),
				)
			],
		)


class WW_001t27:
	"""The Azerite Ox"""

	play = _AzeriteOxDiscover(CONTROLLER)
